language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - git pull
install:
  - npm install
script:
  - sh ./run.sh
after_success:
  - git config user.email "fifi@podentender.com"
  - git config user.name "Dona Fifi"
  - git add aggregated.csv
  - git commit -m "Miniiino, deixa eu te falar!"
  - git push https://${GITHUB_USER}:${GITHUB_API_KEY}@${GH_REF} HEAD:master
